baseURL = 'https://fmhswaterjags.com/'
languageCode = 'en-us'
title = 'FMHS Water Jags'
theme = 'mainroad'

[markup]
  defaultMarkdownHandler = 'goldmark'
[markup.goldmark.renderHooks.image]
    useEmbedded = "fallback"

[Params]
    description = "Flower Mound High School Swim & Dive"
    copyright = "FMHS Water Jags Booster Club"
    dateformat = "2006-01-02"
    customCSS = ["css/custom.css"]
    spiritLink = "https://kristees.biz/collections/flower-mound-swim-and-dive"
    spiritLinkText = "Kristees FMHS Swim & Dive"
    uil = "UIL Conference 6A, Region 2, District 5"
    mainSections = ["posts"]
    googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap"
    # HeaderImage = "2024-district-champsx800.png"

[Params.style.vars]
    highlightColor = "#073772"

[Params.logo]
    image = "img/logos/fm-swim-dive-logo-200.png"
    title = "FMHS Water Jags"
    subtitle = "Flower Mound High School"

[Params.sidebar]
home = "right"
list = false
single = false
widgets = ["dues","photos","recent","meets","wac","social","sponsors"]

[Params.widgets]
  recent_num = 6 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  facebook = "FMHSWaterJag"
  # twitter = "FMHSWaterJags"
  # twitter2 = "waterpolofmhs"
  instagram = "fmswimdive"
  # linkedin = "username"
  # telegram = "username"
  # github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  email = "fmhswaterjags@gmail.com"

[Params.widgets.search]
  cached = false # activate cache if true
  url = "https://google.com/search"
  [Params.widgets.search.input]
    name = "sitesearch"
    pre = ""

##
# menu
##
[Menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[menu.main]]
    name = 'Roster'
    pageRef = '/roster'
    weight = 10
[[menu.main]]
    name = 'Coaches'
    pageRef = '/coaches'
    weight = 20
[[menu.main]]
    name = 'Calendar'
    pageRef = '/calendar'
    weight = 30
[[menu.main]]
    name = 'Meets'
    pageRef = '/meet-schedule'
    weight = 31
[[menu.main]]
    name = 'Records'
    pageRef = '/records'
    weight = 32
# [[menu.main]]
#     name = 'Volunteer'
#     pageRef = '/volunteer'
#     weight = 40
[[menu.main]]
    name = 'Booster Info'
    pageRef = '/booster-info'
    weight = 50
[[menu.main]]
    name = 'Photos'
    pageRef = '/photos'
    weight = 60
[[menu.main]]
    name = 'Spirit Wear'
    url = 'https://kristees.biz/collections/flower-mound-swim-and-dive'
    weight = 70
    [menu.main.params]
        external = true
# [[menu.main]]
#     name = 'Forms'
#     pageRef = '/forms'
#     weight = 80
[[menu.main]]
    name = 'Archive'
    pageRef = '/archive'
    weight = 900
[[menu.main]]
    name = 'FAQ'
    pageRef = '/faq'
    weight = 1000
# [[menu.main]]
#     name = "sub-menu"
#     url = '/forms'
#     parent = "Forms"
## 
# menu footer
##
[[menu.footer]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[menu.footer]]
    name = 'Roster'
    pageRef = '/roster'
    weight = 10
[[menu.footer]]
    name = 'Volunteer'
    pageRef = '/volunteer'
    weight = 40
[[menu.footer]]
    name = 'Booster Info'
    pageRef = '/booster-info'
    weight = 50
[[menu.footer]]
    name = 'Spirit Wear'
    url = 'https://kristees.biz/collections/swim-and-dive'
    weight = 70
    [menu.main.params]
        rel = 'external'
[[menu.footer]]
    name = 'Forms'
    pageRef = '/forms'
    weight = 80